k8ssandra:
  namespace: k8ssandra
cassandra:
  clusterName: cluster1
ingress:
  traefik:
    enabled: true
    repair:
      host: "localhost"
    stargate:
      enabled: true
      host: "localhost"
stargate:
  enabled: true
